const BONUS_FEATURES = [
  { title: 'Treino Pilates em casa', description: 'Aulas guiadas para fortalecer, alongar e treinar sem sair de casa.', price: 'R$ 39,90', image: '/img/bonuses/pilates-em-casa.jpg' },
  { title: '48 fichas de treinos de musculação + Cardio', description: 'Treinos prontos para variar a rotina e evoluir com mais consistência.', price: 'R$ 59,90', image: '/img/bonuses/musculacao-cardio.jpg' },
  { title: '102 Receitas Práticas para Air Fryer', description: 'Receitas rápidas e práticas para aproveitar sua Air Fryer no dia a dia.', price: 'R$ 29,90', image: '/img/bonuses/receitas-air-fryer.jpg' },
  { title: '200 Receitas Fit e Saudáveis', description: 'Opções equilibradas para comer bem sem abrir mão do sabor.', price: 'R$ 49,90', image: '/img/bonuses/receitas-fit.jpg' },
  { title: '200 Receitas de Café da Manhã Nutritivas', description: 'Ideias simples para começar o dia com mais energia e saciedade.', price: 'R$ 39,90', image: '/img/bonuses/receitas-cafe-da-manha.jpg' },
  { title: '100 Receitas Lowcarb práticas', description: 'Receitas práticas com menos carboidratos para facilitar sua rotina.', price: 'R$ 39,90', image: '/img/bonuses/receitas-lowcarb.jpg' },
] as const

export default function BonusFeatures() {
  return <section id="bonus" className="scroll-mt-24 bg-[var(--color-surface-page)] px-5 pb-16 pt-8 sm:pb-24 sm:pt-12"><div className="mx-auto max-w-5xl"><div className="mb-10 text-center"><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.22em] text-[var(--color-brand-burgundy)]">Incluídos no plano completo</p><h2 className="text-[clamp(30px,4vw,50px)] font-semibold leading-[1.06] text-[var(--color-text-primary)]" style={{ fontFamily: 'var(--font-serif)', letterSpacing: '-1.2px' }}>Bônus exclusivos para <em className="italic text-[var(--color-brand-burgundy)]">deixar sua rotina mais leve.</em></h2><p className="mx-auto mt-4 max-w-xl text-[15px] leading-[1.7] text-[var(--color-text-secondary)]">Todos os bônus são liberados diretamente no app junto com o seu acesso vitalício.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{BONUS_FEATURES.map((feature) => <article key={feature.title} className="flex min-h-full flex-col overflow-hidden rounded-[24px] border border-[rgba(68,2,6,0.16)] bg-[#FFF9F1] shadow-[0_18px_48px_-28px_rgba(68,2,6,0.45)]"><div className="aspect-[2/1] overflow-hidden bg-[var(--color-surface-subtle)]"><img src={feature.image} alt="" loading="lazy" decoding="async" className="h-full w-full object-cover" draggable={false} /></div><div className="flex flex-1 flex-col p-5 sm:p-6"><div className="mb-3 flex items-start justify-between gap-3"><h3 className="text-[20px] font-semibold leading-tight text-[var(--color-text-primary)]" style={{ fontFamily: 'var(--font-serif)' }}>{feature.title}</h3><span className="shrink-0 rounded-md bg-[var(--color-brand-burgundy)] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.06em] text-white">Grátis</span></div><p className="text-[13px] leading-[1.65] text-[rgba(38,29,24,0.72)]">{feature.description}</p><p className="mt-auto pt-4 text-[13px] font-bold text-[var(--color-text-muted)] line-through">{feature.price}</p></div></article>)}</div></div></section>
}
