import { useState } from 'react'
import { appendCurrentUtmParams } from '../lib/campaignParams'
import offerCardVisual from '../assets/offer/offer-card-visual.webp'

const COMPLETE_CHECKOUT = 'https://pay.meuglowmode.site/checkout/v5/brfpODwpWq8xHlLVGwn4'
const UPGRADE_CHECKOUT = 'https://pay.meuglowmode.site/checkout/v5/vchTLDDSJPvRSd26ejYZ'
const ESSENTIAL_CHECKOUT = 'https://pay.meuglowmode.site/checkout/v5/fRHH3cKjcuSYO1sIDArR'

const CORE_FEATURES = ['Acesso vitalício ao Zyra', 'Desafio personalizado de rotina', 'Rastreador de hábitos', 'Centralizador de tarefas', 'Organizador de treinos', 'Journal diário', 'Controle financeiro', 'Temas personalizados', 'Notificações em tempo real']
const BONUS_NAMES = ['Treino Pilates em casa', '48 fichas de treinos de musculação + Cardio', '102 Receitas Práticas para Air Fryer', '200 Receitas Fit e Saudáveis', '200 Receitas de Café da Manhã Nutritivas', '100 Receitas Lowcarb práticas']

function FeatureList({ complete }: { complete: boolean }) {
  const items = complete ? [...CORE_FEATURES, ...BONUS_NAMES] : CORE_FEATURES
  return <ul className={`grid gap-3 ${complete ? 'grid-cols-1 sm:grid-cols-2' : 'grid-cols-1'}`}>{items.map((feature) => <li key={feature} className="flex items-start gap-2.5"><span className={`mt-0.5 ${complete ? 'text-[rgba(249,246,240,0.6)]' : 'text-[var(--color-status-success)]'}`}>✓</span><span className={`text-[13px] leading-snug ${complete ? 'text-[rgba(249,246,240,0.62)]' : 'text-[rgba(38,29,24,0.72)]'}`}>{feature}</span></li>)}</ul>
}

function UpgradeModal({ onClose }: { onClose: () => void }) {
  const upgradeUrl = appendCurrentUtmParams(UPGRADE_CHECKOUT)
  const essentialUrl = appendCurrentUtmParams(ESSENTIAL_CHECKOUT)
  return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-[rgba(28,20,16,0.72)] p-3 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="upgrade-title"><div className="relative w-full max-w-[500px] rounded-[28px] bg-[var(--color-surface-page)] px-4 py-7 text-center shadow-2xl sm:px-8 sm:py-8"><button type="button" onClick={onClose} aria-label="Fechar oferta" className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full text-[var(--color-brand-burgundy)] hover:bg-[rgba(68,2,6,0.08)]">×</button><span className="inline-flex rounded-full bg-[rgba(68,2,6,0.08)] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.08em] text-[var(--color-brand-burgundy)]">Oferta exclusiva</span><h2 id="upgrade-title" className="mx-auto mt-4 max-w-[420px] text-[clamp(24px,5vw,30px)] font-semibold leading-[1.16] text-[var(--color-text-primary)]" style={{ fontFamily: 'var(--font-serif)' }}>Espere! Leve o Plano Completo por apenas <span className="text-[var(--color-brand-burgundy)]">R$ 35,90</span></h2><p className="mx-auto mt-3 max-w-[420px] text-[13px] leading-relaxed text-[var(--color-text-secondary)]">Por apenas R$ 3 a mais, leve todos os seis bônus exclusivos e aproveite ainda mais sua jornada no Zyra.</p><ul className="mt-5 grid gap-2 rounded-[20px] border border-[var(--color-border-default)] bg-white px-4 py-4 text-left sm:gap-3 sm:px-5 sm:py-5">{BONUS_NAMES.map((bonus) => <li key={bonus} className="flex items-start gap-2 text-[12px] font-semibold leading-snug text-[var(--color-text-primary)] sm:text-[13px]"><span className="mt-0.5 text-[var(--color-brand-burgundy)]">✓</span>{bonus}</li>)}</ul><a href={upgradeUrl} target="_blank" rel="noopener noreferrer" className="checkout-cta mt-5 flex min-h-14 w-full items-center justify-center gap-2 rounded-[20px] px-4 text-[13px] font-bold text-white shadow-[0_12px_24px_rgba(68,2,6,0.2)] transition hover:-translate-y-0.5 sm:mt-6 sm:text-[14px]">Sim, quero o Plano Completo com desconto <span aria-hidden="true">→</span></a><a href={essentialUrl} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-[12px] font-semibold text-[var(--color-text-muted)] underline underline-offset-2 sm:text-[13px]">Não quero adicionar os bônus</a></div></div>
}

type PricingProps = { variant?: 'default' | 'humor' }

export default function Pricing({ variant = 'default' }: PricingProps) {
  const [upgradeOpen, setUpgradeOpen] = useState(false)
  const completeUrl = appendCurrentUtmParams(COMPLETE_CHECKOUT)
  const isHumor = variant === 'humor'

  return <section id="pricing" className="px-5 py-16 sm:py-24"><div className="mx-auto max-w-5xl"><div className="mb-14 text-center"><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.22em] text-[var(--color-brand-burgundy)]">Escolha seu acesso</p><h2 className="mb-4 text-[clamp(32px,4.2vw,56px)] font-semibold leading-[1.06] text-[var(--color-text-primary)]" style={{ fontFamily: 'var(--font-serif)', letterSpacing: '-1.5px' }}>{isHumor ? <>Cuide da sua mente. <em className="italic text-[var(--color-brand-burgundy)]">Organize sua vida.</em></> : <>Organize sua rotina. <em className="italic text-[var(--color-brand-burgundy)]">Viva com mais leveza.</em></>}</h2><p className="mx-auto max-w-lg text-[16px] leading-[1.75] text-[var(--color-text-secondary)]">Comece hoje com pagamento único e acesso vitalício ao Zyra.</p></div><div className="grid items-stretch gap-5 lg:grid-cols-2">
    <article className="card-spotlight flex flex-col rounded-[28px] border border-[var(--color-border-default)] bg-white p-7 shadow-[0_18px_48px_-28px_rgba(68,2,6,0.35)] sm:p-8"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--color-text-muted)]">Somente o app</p><h3 className="mt-2 text-[32px] font-semibold leading-tight text-[var(--color-text-primary)]" style={{ fontFamily: 'var(--font-serif)' }}>Zyra Essencial</h3><p className="mt-3 max-w-sm text-[14px] leading-[1.65] text-[var(--color-text-secondary)]">Tudo para organizar sua rotina em um único lugar.</p><div className="mt-7 border-y border-[var(--color-border-subtle)] py-6"><p className="text-[13px] font-medium text-[var(--color-text-muted)]">De <span className="line-through">R$ 75,90</span> por</p><p className="mt-1 text-[56px] font-semibold leading-none text-[var(--color-brand-burgundy)]" style={{ fontFamily: 'var(--font-serif)' }}>R$ 32,90</p><p className="mt-2 text-[12px] text-[var(--color-text-secondary)]">Pagamento único · acesso vitalício</p></div><FeatureList complete={false} /><button type="button" onClick={() => setUpgradeOpen(true)} className="mt-8 flex min-h-[52px] w-full items-center justify-center rounded-[24px] border-2 border-[var(--color-brand-burgundy)] px-4 text-[14px] font-bold text-[var(--color-brand-burgundy)] transition hover:-translate-y-0.5">Quero apenas o Zyra</button></article>
    <article className="relative flex flex-col overflow-visible rounded-[28px] border border-[rgba(249,246,240,0.1)] bg-[var(--color-text-primary)] shadow-[0_32px_80px_rgba(28,20,16,0.3)] transition-transform duration-300 hover:-translate-y-1"><div className="absolute -top-3.5 left-1/2 z-10 -translate-x-1/2"><span className="inline-flex items-center gap-1.5 whitespace-nowrap rounded-full bg-[var(--color-surface-page)] px-3.5 py-1.5 text-[11px] font-bold text-[var(--color-brand-burgundy)] shadow-[0_6px_16px_rgba(28,20,16,0.22)]"><span className="h-1.5 w-1.5 rounded-full bg-current opacity-55" />Mais escolhido</span></div><div className="flex flex-1 flex-col p-7 sm:p-8"><div className="grid gap-6 sm:grid-cols-[1.05fr_0.95fr] sm:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[rgba(249,246,240,0.5)]">App + 6 bônus</p><h3 className="mt-2 text-[32px] font-semibold leading-tight text-[var(--color-surface-page)]" style={{ fontFamily: 'var(--font-serif)' }}>Zyra Completo</h3><p className="mt-3 text-[14px] leading-[1.65] text-[rgba(249,246,240,0.5)]">A experiência completa para cuidar de todas as áreas da sua vida.</p></div><div className="relative flex justify-center sm:justify-end"><div className="absolute inset-x-8 bottom-3 h-14 rounded-full bg-[rgba(249,246,240,0.14)] blur-2xl" /><img src={offerCardVisual} alt="Prévia do Zyra" className="relative w-full max-w-[220px] drop-shadow-[0_24px_32px_rgba(0,0,0,0.35)]" loading="lazy" draggable={false} /></div></div><div className="my-7 rounded-[24px] border border-[rgba(249,246,240,0.13)] bg-gradient-to-b from-[rgba(249,246,240,0.085)] to-[rgba(249,246,240,0.045)] px-5 py-5 sm:px-6 sm:py-6"><div className="flex items-baseline justify-between gap-3"><p className="text-[13px] font-medium text-[rgba(249,246,240,0.42)]">De <span className="line-through">R$ 95,90</span> por</p><span className="text-[11px] font-bold uppercase tracking-[0.14em] text-[#D7C6A8]">acesso vitalício</span></div><div className="my-5 border-t border-[rgba(249,246,240,0.1)]" /><p className="mb-1 text-[13px] font-semibold uppercase tracking-[0.12em] text-[rgba(249,246,240,0.5)]">Pagamento único</p><p className="text-[clamp(58px,9vw,82px)] font-semibold leading-[0.86] text-[var(--color-surface-page)]" style={{ fontFamily: 'var(--font-serif)', letterSpacing: '-1px' }}>R$ 47,90</p></div><a href={completeUrl} target="_blank" rel="noopener noreferrer" className="btn-fill checkout-cta mb-7 flex min-h-[52px] w-full items-center justify-center gap-2 rounded-[24px] px-4 py-3 text-center text-[14px] font-semibold transition-all hover:-translate-y-0.5 active:scale-[0.98]">Quero o Zyra Completo <span aria-hidden="true">→</span></a><div className="mb-5 border-t border-[rgba(249,246,240,0.09)]" /><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.12em] text-[rgba(249,246,240,0.28)]">Tudo incluso no plano</p><FeatureList complete /></div></article>
  </div></div>{upgradeOpen ? <UpgradeModal onClose={() => setUpgradeOpen(false)} /> : null}</section>
}
